title: "Jekyll-Theme-MDUI"
description: "A Jekyl Theme Based on MDUI"
url: 
baseurl: "/jekyll-theme-mdui"
author: "Mysaku"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
  - CHANGELOG.md